// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlpdjuzbjytkkoqvwwld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscGRqdXpianl0a2tvcXZ3d2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDU5NzIsImV4cCI6MjA2NzIyMTk3Mn0.0PFTbJx8Rdx0Ph2WJL6bZ9cFopB6y_sUOYdYMKswHyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});